name: open_weather_client
description: Unofficial OpenWeather package for Current and Forecast weather data.
version: 1.0.4
homepage: 'https://github.com/csongorkeller/flutter_open_weather_package'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  transparent_image: ^1.0.0
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
