name: open_weather_client
description: OpenWeather package for Current and Forecast weather data.
version: 2.4.0
homepage: "https://github.com/csongorkeller/flutter_open_weather_package"

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  transparent_image: ^2.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  flutter_lints: any
